### PR TITLE
Add `@Statement` macro

### PR DESCRIPTION
**Pull request by lovetodream**
## Declaration

This adds a protocol `OraclePreparedStatement`, to allow creating and executing SQL statements in a structured way.

```swift
struct UsersStatement: OraclePreparedStatement {
    static let sql = "SELECT id, name, age FROM users WHERE :1 < age"

    typealias Row = (UUID, String, Int)

    var age: Int

    func makeBindings() -> OracleBindings {
        var bindings = OracleBindings()
        bindings.append(age, context: .default, bindName: "1")
        return bindings
    }

    func decodeRow(_ row: OracleRow) throws -> Row {
        try row.decode(Row.self)
    }
}
```

### Declare using Macro

Furthermore it allows us to create these using a powerful `@Statement` macro. 
Macros are not part of the `OracleNIO` module, the `OracleNIOMacros` module has to be imported by the caller.
The same code as the one above can be created using two lines of code.

```swift
import OracleNIOMacros

@Statement("SELECT \("id", Int.self), \("name", String.self), \("age", Int.self) FROM users WHERE \(bind: "age", OracleNumber.self) < age")
struct UsersStatement {}
```

The macro adds even more convenience, it expands to the following code:

```swift
struct UsersStatement {
    struct Row {
        var id: Int
        var name: String
        var age: Int
    }

    static let sql = "SELECT id, name, age FROM users WHERE :1 < age"
    
    var age: OracleNumber

    func makeBindings() throws -> OracleBindings {
        var bindings = OracleBindings(capacity: 1)
        bindings.append(age, context: .default, bindName: "1")
        return bindings
    }

    func decodeRow(_ row: OracleRow) throws -> Row {
        let (id, name, age) = try row.decode((Int, String, Int).self)
        return Row(id: id, name: name, age: age)
    }
}
extension UsersStatement: OraclePreparedStatement {}
```

> All this is happening at compile time and adds no overhead to the actual queries being performed.

## Querying

The statement can now be used similar to normal `OracleStatement`s.

```swift
let connection: OracleConnection = ...
let stream = try await connection.execute(UsersStatement(age: 18))
for try await user in stream {
    print(user.id, user.name, user.age)
}
```

### CODE REVIEW

**Comment by Tommynocker** [comment]
How I import OracleNIOMacros in swift?

**Comment by lovetodream** [comment]
Currently you have to go to your `Package.swift` and change the version of oracle-nio to this branch and add `OracleNIOMacros` to the dependencies of your target.
```swift
dependencies: [
    .package(url: "https://github.com/lovetodream/oracle-nio.git", branch: "statement-macro")
],
targets: [
    .target(
        name: "PostgresNIOMacros",
        dependencies: [
            ...
            .product(name: "OracleNIO", package: "oracle-nio")
            .product(name: "OracleNIOMacros", package: "oracle-nio")
        ]
    )
]
```

Then you can use OracleNIOMacros as you would use anything else, just import it on the top of your file.

> Note: It is still in development and might contain various bugs/not compile at all for 5.x Swift versions!

**Comment by Tommynocker** [comment]
Is there an example Project anywhere ?

**Comment by lovetodream** [comment]
> Is there an example Project anywhere ?

Not yet, it is still subject to change

**Pull request merged**
